package com.longuto.androidtemplet.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.longuto.androidtemplet.model.greendao.LogcollectionInfo;

import com.longuto.androidtemplet.greendao.db.LogcollectionInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig logcollectionInfoDaoConfig;

    private final LogcollectionInfoDao logcollectionInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        logcollectionInfoDaoConfig = daoConfigMap.get(LogcollectionInfoDao.class).clone();
        logcollectionInfoDaoConfig.initIdentityScope(type);

        logcollectionInfoDao = new LogcollectionInfoDao(logcollectionInfoDaoConfig, this);

        registerDao(LogcollectionInfo.class, logcollectionInfoDao);
    }
    
    public void clear() {
        logcollectionInfoDaoConfig.clearIdentityScope();
    }

    public LogcollectionInfoDao getLogcollectionInfoDao() {
        return logcollectionInfoDao;
    }

}
